defaultEntryPoints = ["http"]

# Entrypoints, http and https
[web]
  address = ":8080"

[entryPoints]

  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
#    entryPoint = "http"
  # https is the default
#  [entryPoints.https]
#  address = ":443"
#    [entryPoints.https.tls]

# Enable ACME (Let's Encrypt): automatic SSL
#[acme]
# Email address used for registration
#email = "cristiano@mundodocker.con.br"
#storageFile = "/etc/traefik/acme/acme.json"
#entryPoint = "https"
#onDemand = false
#OnHostRule = true
  # Use a HTTP-01 acme challenge rather than TLS-SNI-01 challenge
#  [acme.httpChallenge]
#  entryPoint = "http"

# Enable Docker configuration backend
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "mundodocker.com.br"
watch = true
